---
#System Settings
php_modules: [ 'php-curl', 'php-gd', 'php-mbstring', 'php-xml', 'php-xmlrpc', 'php-soap', 'php-intl', 'php-zip' ]

#Nginx Settings
http_host: "localhost"
http_conf: "localhost.conf"
#http_port: "80"

#MySQL Settings
mysql_root_password: "mysql_root_password"
mysql_db: "wordpress"
mysql_user: "wordpress"
mysql_password: "password"

user: iitbdrf
wp_dir: wordpress