---
#System Settings
php_modules: [ 'php8.0-curl', 'php8.0-gd', 'php8.0-mbstring', 'php8.0-xml', 'php8.0-xmlrpc', 'php8.0-soap', 'php8.0-intl', 'php8.0-zip' ]

#Nginx Settings
http_host: "localhost"
http_conf: "localhost.conf"
#http_port: "80"

#MySQL Settings
mysql_root_password: "mysql_root_password"
mysql_db: "wordpress"
mysql_user: "wordpress"
mysql_password: "password"

user: iitbdrf
wp_dir: wordpress