---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml
  vars:
    proxy_env:
      http_proxy: http://10.199.4.240:3128/
      https_proxy: http://10.199.4.240:3128/
  
  tasks:
    - name: Download and unpack latest Prometheus
      unarchive:
        src: https://github.com/prometheus/prometheus/archive/refs/heads/main.zip
        dest: "/root/"
        remote_src: yes
      tags: [ prometheus ]
