---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml
  
  tasks:
    - name: Install git
      yum: name={{ item }} update_cache=yes state=latest
      loop: [ 'git' ]
      tags: [ system ]

    - name: Get prometheus
      shell: "git clone https://github.com/prometheus/prometheus.git"
      tags: [ wordpress ]