---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml
  vars:
    proxy_env:
      http_proxy: http://10.199.4.240:3128/
      https_proxy: http://10.199.4.240:3128/
  
  tasks:
    - name: Download and unpack latest Prometheus
      unarchive:
        src: https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
        dest: "/home/iitbdrf"
        remote_src: yes
      tags: [ node_explorer ]

    - name: Copy the node_exporter service file
      template:
        src: "files/node_exporter.service.j2"
        dest: "/etc/systemd/system/node_exporter.service"
      tags: [ node_explorer ]    

    - name: Start and enable node_explorer service, in all cases, also issue daemon-reload to pick up config changes
      ansible.builtin.systemd:
        state: started
        daemon_reload: yes
        name: node_explorer
        enabled: yes

- hosts: localhost
  become: true
  vars_files:
    - vars/default.yml