---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml
  
  tasks:
    - name: Install git
      yum: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: [ 'git' ]
      tags: [ system ]
    - name: Create git archive from repo
      ansible.builtin.git:
      repo: https://github.com/prometheus/prometheus.git
      dest: /root/
      archive: /root/ansible-examples.zip

