#########################################################
# Auto Server Haredening Script
#########################################################
---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Update & upgrade apt packges
      apt: 
        force_apt_get: yes
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day
      tags: [ system ]

    - name: Install Firewalld, auditd, rsyslog, rsyslog-mysql, fail2ban
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: [ 'firewalld', 'auditd', 'rsyslog', 'rsyslog-mysql', 'chrony', 'fail2ban', 'aide' ]
      tags: [ system ]

    - name: Enable services on system reboot
      service: name={{ item }} enabled=yes
      loop: [ 'firewalld', 'auditd', 'rsyslog', 'chrony', 'fail2ban', 'aide' ]

    - name: Start services
      service: name={{ item }} state=started
      loop: [ 'firewalld', 'auditd', 'rsyslog', 'chrony', 'fail2ban', 'aide' ]

    - name: Add ports
      firewalld:
        permanent: yes
        immediate: yes
        service: "{{item}}"
        state: enabled
      with_items:
       - http
       - https
       - ssh
       - rsyncd

    - name: Manage outbound rules
      template:
        src: files/direct.xml.j2
        dest: /etc/firewalld/direct.xml
      notify: reload_firewalld

    - name: Copy /etc/sysctl.conf file
      template:
        src: files/sysctl.conf.j2
        dest: /etc/sysctl.conf

    - name: Copy /etc/audit file
      template:
        src: files/sysctl.conf.j2
        dest: /etc/sysctl.conf
      notify: restart_auditd

    - name: Copy /etc/ssh/sshd_config file
      template:
        src: files/sshd_config.j2
        dest: /etc/ssh/sshd_config
      notify: restart_sshd

    - name: Copy /etc/chrony/chrony.conf file
      template:
        src: files/chrony.conf.j2
        dest: /etc/chrony/chrony.conf
      notify: restart_chronyd

    - name: Touch the /etc/cron.allow file
      file:
        path: /etc/cron.allow
        state: touch

    - name: Transfer the userdotfilecheck.sh script
      copy:
        src: files/userdotfilecheck.sh.j2
        dest: /root/userdotfilecheck.sh

    - name: Execute the veryuseful.sh script
      command: bash /root/veryuseful.sh

  handlers:
    - name: reload_firewalld
      service:
        name: firewalld
        state: reloaded
    - name: restart_auditd
      service:
        name: auditd
        state: restart
    - name: restart_sshd
      service:
        name: sshd
        state: restart
    - name: restart_sshd
      service:
        name: sshd
        state: restart
    - name: restart_chronyd
      service:
        name: chronyd
        state: restart












