#########################################################
# Auto Server Haredening Script
#########################################################
---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Update & upgrade apt packges
      apt: 
        force_apt_get: yes
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day
      tags: [ system ]

    - name: Install firewalld
      action: apt name=firewalld state=latest

    - name: Enable firewalld on system reboot
      service: name=firewalld enabled=yes

    - name: Start Firewalld
      service: name=firewalld state=started

    - name: Add ports
      firewalld:
        permanent: yes
        immediate: yes
        service: "{{item}}"
        state: enabled
      with_items:
       - http
       - https
       - ssh
       - rsyncd

    - name: Manage outbound rules
      template:
        src: files/direct.xml.j2
        dest: /etc/firewalld/direct.xml
      notify: reload_firewalld

    - name: Copy /etc/sysctl.conf file
      template:
        src: files/sysctl.conf.j2
        dest: /etc/sysctl.conf

  handlers:
    - name: reload_firewalld
      service:
        name: firewalld
        state: reload















