#########################################################
# Auto Server Haredening Script
#########################################################
---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Update & upgrade apt packges
      apt: 
        force_apt_get: yes
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day
      tags: [ system ]

