#########################################################
# Auto Server Haredening Script
#########################################################
---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Update & upgrade apt packges
      apt: 
        force_apt_get: yes
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day
      tags: [ system ]

    - name: Install Firewalld, auditd, rsyslog, rsyslog-mysql
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: [ 'firewalld', 'auditd', 'rsyslog', 'rsyslog-mysql' ]
      tags: [ system ]

    - name: Enable services on system reboot
      service: name={{ item }} enabled=yes
      loop: [ 'firewalld', 'auditd', 'rsyslog', 'rsyslog-mysql' ]

    - name: Start services
      service: name={{ item }} state=started
      loop: [ 'firewalld', 'auditd', 'rsyslog', 'rsyslog-mysql' ]

    - name: Add ports
      firewalld:
        permanent: yes
        immediate: yes
        service: "{{item}}"
        state: enabled
      with_items:
       - http
       - https
       - ssh
       - rsyncd

    - name: Manage outbound rules
      template:
        src: files/direct.xml.j2
        dest: /etc/firewalld/direct.xml
      notify: reload_firewalld

    - name: Copy /etc/sysctl.conf file
      template:
        src: files/sysctl.conf.j2
        dest: /etc/sysctl.conf

    - name: Copy /etc/audit file
      template:
        src: files/sysctl.conf.j2
        dest: /etc/sysctl.conf
      notify: restart_auditd

    - name: Copy /etc/ssh/sshd_config file
      template:
        src: files/sshd_config.j2
        dest: /etc/ssh/sshd_config
      notify: restart_sshd

  handlers:
    - name: reload_firewalld
      service:
        name: firewalld
        state: reload
    - name: restart_auditd
      service:
        name: auditd
        state: restart














